import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface GenerateMessageRequest {
  type: "inmail" | "email";
  recipientName: string;
  recipientFirstName: string;
  companyName?: string;
  eventDetail?: string;
  jobTitle?: string;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { type, recipientName, recipientFirstName, companyName, eventDetail, jobTitle }: GenerateMessageRequest = await req.json();
    const ANTHROPIC_API_KEY = Deno.env.get("ANTHROPIC_API_KEY");

    if (!ANTHROPIC_API_KEY) {
      throw new Error("ANTHROPIC_API_KEY is not configured");
    }

    const systemPrompt = `Tu es un expert en rédaction commerciale B2B haut de gamme pour Gourrmet, spécialiste des cadeaux d'affaires de luxe (coffrets gastronomiques, champagnes, créations sur-mesure).

Ton style :
- Élégant et raffiné, jamais familier ni trop commercial
- Personnalisé et contextuel, jamais générique
- Concis mais impactant
- Professionnel mais chaleureux

L'expéditeur est Patrick Oualid, fondateur de Gourrmet.
Contact : +33 7 83 31 94 43 | patrick.oualid@gourrmet.com | www.gourrmet.com`;

    let userPrompt = "";

    if (type === "inmail") {
      userPrompt = `Rédige un message LinkedIn InMail de prospection pour :
- Destinataire : ${recipientFirstName} ${recipientName.split(' ').slice(1).join(' ')}
${jobTitle ? `- Poste : ${jobTitle}` : ''}
${companyName ? `- Entreprise : ${companyName}` : ''}
${eventDetail ? `- Contexte/Actualité : ${eventDetail}` : '- Pas de contexte spécifique'}

Règles :
- Maximum 200 mots
- Commence par une accroche personnalisée liée au contexte/actualité si disponible
- Propose subtilement les services Gourrmet comme partenaire pour marquer cet événement
- Inclus les coordonnées de Patrick à la fin
- Ton chaleureux mais professionnel
- Ne mets pas de crochets ni de placeholders

Génère uniquement le message, sans commentaires.`;
    } else {
      userPrompt = `Rédige un email de prospection pour :
- Destinataire : ${recipientFirstName} ${recipientName.split(' ').slice(1).join(' ')}
${jobTitle ? `- Poste : ${jobTitle}` : ''}
${companyName ? `- Entreprise : ${companyName}` : ''}
${eventDetail ? `- Contexte/Actualité : ${eventDetail}` : '- Pas de contexte spécifique'}

Règles :
- Maximum 250 mots pour le corps
- Génère aussi un objet d'email accrocheur (max 60 caractères)
- Commence par une accroche personnalisée liée au contexte/actualité si disponible
- Présente Gourrmet et ses services (coffrets gastronomiques haut de gamme, champagnes, créations sur-mesure)
- Propose d'accompagner l'entreprise pour marquer cet événement
- Inclus les coordonnées de Patrick à la fin
- Ton professionnel et élégant
- Ne mets pas de crochets ni de placeholders

Format de réponse :
OBJET: [l'objet de l'email]
---
[le corps de l'email]`;
    }

    console.log("Calling Claude Opus with prompt for:", type, recipientName);

    const response = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "x-api-key": ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "claude-opus-4-1-20250805",
        max_tokens: 1024,
        messages: [
          {
            role: "user",
            content: userPrompt,
          },
        ],
        system: systemPrompt,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("Anthropic API error:", response.status, errorText);
      
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: "Rate limit exceeded. Please try again later." }),
          { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      
      throw new Error(`Anthropic API error: ${response.status}`);
    }

    const data = await response.json();
    const generatedText = data.content?.[0]?.text;

    if (!generatedText) {
      throw new Error("No text generated by Claude");
    }

    // Parse email format if needed
    let result: { message: string; subject?: string } = { message: generatedText };
    
    if (type === "email" && generatedText.includes("OBJET:")) {
      const parts = generatedText.split("---");
      const subjectLine = parts[0].replace("OBJET:", "").trim();
      const body = parts.slice(1).join("---").trim();
      result = { message: body, subject: subjectLine };
    }

    return new Response(
      JSON.stringify(result),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Error generating message:", error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
