import * as React from 'npm:react@18.3.1'
import {
  Body,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Link,
  Preview,
  Section,
  Text,
} from 'npm:@react-email/components@0.0.22'
import type { TemplateEntry } from './registry.ts'

interface OutreachMessageProps {
  subject?: string
  bodyHtml?: string
  senderName?: string
  recipientFirstName?: string
  signalCompany?: string
  unsubscribeUrl?: string
}

const OutreachMessage = ({
  subject = 'Une attention de la part de GOURЯMET',
  bodyHtml = '',
  senderName = 'Clotilde Gautier',
  recipientFirstName,
  signalCompany,
}: OutreachMessageProps) => {
  const greeting = recipientFirstName ? `Bonjour ${recipientFirstName},` : 'Bonjour,'

  return (
    <Html lang="fr" dir="ltr">
      <Head />
      <Preview>{subject}</Preview>
      <Body style={main}>
        <Container style={container}>
          <Heading style={brand}>GOURЯMET</Heading>

          <Section style={section}>
            <Text style={text}>{greeting}</Text>
            {/* bodyHtml is generated by our own AI on the server — trusted source */}
            <div
              style={bodyStyle}
              dangerouslySetInnerHTML={{ __html: bodyHtml }}
            />
            <Text style={signature}>
              Bien à vous,
              <br />
              {senderName}
              <br />
              <span style={role}>GOURЯMET</span>
            </Text>
          </Section>

          {signalCompany ? (
            <>
              <Hr style={hr} />
              <Text style={footnote}>
                Vous recevez ce message car nous avons identifié une actualité concernant{' '}
                <strong>{signalCompany}</strong>.
              </Text>
            </>
          ) : null}
        </Container>
      </Body>
    </Html>
  )
}

export const template = {
  component: OutreachMessage,
  subject: (data: Record<string, unknown>) =>
    (data.subject as string) || 'Une attention de la part de GOURЯMET',
  displayName: 'Message de prospection',
  previewData: {
    subject: 'Félicitations pour votre nouvelle levée',
    bodyHtml: '<p>Toutes nos félicitations pour cette belle annonce…</p>',
    senderName: 'Clotilde Gautier',
    recipientFirstName: 'Marie',
    signalCompany: 'Acme SAS',
  },
} satisfies TemplateEntry

const main = {
  backgroundColor: '#ffffff',
  fontFamily: 'Poppins, Helvetica, Arial, sans-serif',
  color: '#1a1a1a',
}
const container = { padding: '32px 24px', maxWidth: '600px', margin: '0 auto' }
const brand = {
  fontFamily: 'Montserrat, Helvetica, Arial, sans-serif',
  fontSize: '28px',
  fontWeight: 700,
  letterSpacing: '0.08em',
  color: '#E8735A',
  margin: '0 0 24px',
}
const section = { padding: '0' }
const text = { fontSize: '15px', lineHeight: '1.6', margin: '0 0 16px' }
const bodyStyle = { fontSize: '15px', lineHeight: '1.7', color: '#1a1a1a' }
const signature = { fontSize: '15px', lineHeight: '1.6', marginTop: '24px' }
const role = { color: '#6b6b6b', fontSize: '13px' }
const hr = { borderColor: '#eee', margin: '32px 0 16px' }
const footnote = { fontSize: '12px', color: '#6b6b6b', lineHeight: '1.5' }
